name: montageapp
description: A new Flutter application.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.3
  equatable: ^1.2.2
  dartz: ^0.9.1
  data_connection_checker: ^0.3.4
  http: ^0.12.1
  flutter_bloc: ^5.0.1
  get_it: ^4.0.2
  sqflite: ^1.3.0
  path_provider: ^1.5.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^4.1.1
  bloc_test: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/man_1.png
    - assets/man_2.png
    - assets/man_3.png
    - assets/man_4.png
    - assets/man_5.png
    - assets/man_6.png
    - assets/man_7.png
    - assets/woman_1.png
    - assets/woman_2.png
    - assets/woman_3.png
    - assets/woman_4.png
    - assets/woman_5.png
    - assets/woman_6.png
    - assets/woman_7.png
